baseURL = ""
languageCode = "en-us"
title = "Feex | The home upkeep specialist"
staticDir = ["assets", "static" ]

[params]
    feexWizardURL = "https://localhost:8000/app/wizard/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true