[build]
publish = "public"
command = "hugo --gc --minify --logLevel=info"
environment = { HUGO_VERSION = "0.120.4", HUGO_ENABLEGITINFO = "true", NODE_ENV = "production", HUGO_ENV = "production" }

[context.staging]
command = "hugo --gc -v"
environment = { NODE_ENV = "production", HUGO_ENV = "staging" }

